### PR TITLE
Handle primitive json responses

### LINKED ISSUE #363: HTTP calls returning an int result in a class cast exception
For example, an http get which responds with just an int or a string throws a class cast exception.  That's perfectly valid json so we should support it.

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map
	at com.twosigma.webtau.http.Http.createBodyDataNode(Http.java:564)
	at com.twosigma.webtau.http.Http.validateAndRecord(Http.java:494)
	at com.twosigma.webtau.http.Http.lambda$createHttpStep$3(Http.java:451)
	... 57 more
```

### PR DESCRIPTION
**Pull request by tsiq-karold**
fixes #363

### CODE REVIEW

File: webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy [hunk 1]
```diff
@@ -1159,6 +1159,17 @@ class HttpGroovyTest implements HttpConfiguration {
...
 
+    @Test
+    void "handles integer json responses"() {
+        def ret = http.get('/integer') {
+            body.should == 123
+            return body
+        }
+
+        ret.should == 123
+        ret.getClass() == Integer
```
Comment (MykolaGolubyev) [inline webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy]: missing `should`

File: webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java [hunk 2]
```diff
@@ -270,6 +270,18 @@ public void queryParams() {
...
+        Integer ret = http.get("/integer", (header, body) -> {
+            body.should(equal(123));
+            return body;
+        });
+
+        actual(ret).should(equal(123));
+        actual(ret.getClass()).should(equal(Integer.class));
+    }
+
+
```
Comment (MykolaGolubyev) [inline webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java]: extra space

File: webtau-http/src/main/java/com/twosigma/webtau/http/Http.java [hunk 3]
```diff
@@ -558,11 +558,8 @@ private DataNode createBodyDataNode(HttpResponse response) {
             }
 
             if (response.isJson()) {
-                Object mapOrList = JsonUtils.deserialize(response.getTextContent());
-
-                return mapOrList instanceof List ?
-                        DataNodeBuilder.fromList(id, (List<Object>) mapOrList) :
-                        DataNodeBuilder.fromMap(id, (Map<String, Object>) mapOrList);
+                Object object = JsonUtils.deserialize(response.getTextContent());
```
Comment (MykolaGolubyev) [inline webtau-http/src/main/java/com/twosigma/webtau/http/Http.java]: smart!
